name: CI/CD
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Bundle
        run: yarn bundle
      - name: Bundle minified
        run: NODE_ENV=production yarn bundle
      - name: Release
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release

  publish:
    name: Publish
    needs: test
    if: contains(github.ref, 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - uses: actions/cache@v1
        id: yarn2-cache
        with:
          path: storybook/node_modules
          key: ${{ runner.os }}-node_modules2-${{ hashFiles('**/storybook/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules2-
      - name: Install example
        if: steps.yarn2-cache.outputs.cache-hit != 'true'
        run: cd storybook && yarn install
      - name: Build storybook
        run: cd storybook && yarn storybook:build
      
      
  notify:
    name: Notify
    runs-on: ubuntu-latest
    if: failure()
    needs:
      - test
    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()